name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Change to specific version
    steps:
      - name: Checkout repository # Obtain the code from the repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry # Authenticate to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image # Build the Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest .

      - name: Push Docker Image # Push the Docker image to the registry
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Deploy to Server # Deploy the Docker image to the server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
            docker stop app_container || true
            docker rm app_container || true
            docker run -d --name app_container -p 80:80 ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
