name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Change to specific version
    steps:
      - name: Checkout repository # Obtain the code from the repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry # Authenticate to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
