name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Change to specific version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        run: ls -la
